# Site settings
title: Paul Barrett
email: waves@paulbarrettdev.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.paulbarrettdev.com" # the base hostname & protocol for your site
twitter_username: paulbarrett79
github_username:  paulbarrett79

# Build settings
markdown: kramdown

intro: ""

portfolio:
  - title: "Year Of The Fiery Horse"
    weblink: "http://www.yotfh.com"
    description: > # 
      A website using Jekyll for my brother's band Year Of The Fiery Horse. They're based in Liverpool. 
      I originally built a single page site which acted as an aggregator for their social media presence and also 
      their music online. The band then wanted the site redesigned to fit with their E.P. cover designs as well as having a 
      simple "newsfeed". I thought that Jekyll was a good fit for that as it didn't need a lot of dynamic elements. 
      I have plans to migrate this again to Wordpress or another alternative like Ghost so the guys can update news 
      on there themselves.
    thumb: "yotfh-thumb.png"

  - title: "ChemBio Hub"
    weblink: "http://chembiohub.ox.ac.uk"
    description: > #  
      A website again using Jekyll for my current role as web developer at the University of Oxford. 
      I had to make this fit the colour scheme and branding guidelines of the University as well as look clean and professional 
      to show to external funding bodies and University policy makers. I had regular feedback from various stakeholders and 
      made appropriate additions based on that. All of our work within ChemBio Hub is open source and designed to foster 
      collaboration between chemical and biological researchers as well as reduce duplication of effort.
    thumb: "cbh-thumb.png"

  - title: "The SGC"
    weblink: "http://www.thesgc.org"
    description: > #  
      This was a Drupal install which I set up to replace a basic PHP site for The Structural Genomics Consortium (SGC) within University of Oxford. 
      We went through a few iterations in terms of the design, information architecture and theming. 
      I last had involvement in 2014 but the site retains a lot of the core work I did. For example, the Structure Gallery 
      at <a href="http://www.thesgc.org/structures" target="_blank">www.thesgc.org/structures/</a> is a jQuery and Isotope based filter I built 
      which allows an external database to be viewed within Drupal.
    thumb: "sgc-thumb.png"

uxportfolio:
 - title: "ChemBiog user profile designs"
   description: > #
     As part of the ChemBio Hub project, we had one prospective idea of having a social network for postdoctoral and postgraduate 
     research scientists who didn't have as much of a web presence as project leaders. I was asked to come up with some designs of how 
     such an application might work and also designs of some embeddable widgets which could be used within departmental sites. Although this 
     work was temporarily postponed due to more urgent commitments, it could still be used by future incumbents of the project.
   thumbs:
     - "/assets/Mockups/chembiog/individual-widget-1.png"
     - "/assets/Mockups/chembiog/individual-widget-1.png"
     - "/assets/Mockups/chembiog/individual-widget-1.png"
     - "/assets/Mockups/chembiog/individual-widget-1.png"

 - title: "ChemBio Hub search redesign"
   description: > #
     As part of the ChemBio Hub project, we had one prospective idea of having a social network for postdoctoral and postgraduate 
     research scientists who didn't have as much of a web presence as project leaders. I was asked to come up with some designs of how 
     such an application might work and also designs of some embeddable widgets which could be used within departmental sites. Although this 
     work was temporarily postponed due to more urgent commitments, it could still be used by future incumbents of the project.
   thumbs:
     - "/assets/Mockups/chembiog/individual-widget-1.png"